### PR TITLE
Fix for running tox on build servers

### PR DESCRIPTION
**Pull request by kbujold**
Story: 2003408
Task: 24549

Signed-off-by: Kristine Bujold <kristine.bujold@windriver.com>

### CODE REVIEW

**Comment by tylersmith22** [comment]
Looks good.  I'm unsure if this would be welcomed upstream, I don't think it would negatively affect anyone, but it's only an issue for us because of our shared build servers...

**Comment by kbujold** [comment]
I updated the comments and also ported another fix in the same file.

**Comment by tylersmith22** [comment]
Thanks Kristine, looks good

**Comment by dtroyer** [comment]
This arguably should be upstreamed as that is an incomplete method for constructing a temp filename.  The bug should have been filed in Horizon though to do that...

**Pull request merged**
