### PR TITLE
Remove unused new_token code

### PR DESCRIPTION
**Pull request by dsullivanwr**
If a horizon user's token expires during long running operations, those 
operations can fail. This occured during long running heat operations
(eg multiple stack deletions).  Previously we attempted to address this by 
extending the token. The token can not be extended and this code does not 
work as intended. This commit will remove the unused newtoken code.

The issue will be addressed by setting the TOKEN_TIMEOUT_MARGIN parameter
in horizon's local_settings.py

Partial-Bug: 1797186
Signed-off-by: David Sullivan <david.sullivan@windriver.com>

### CODE REVIEW

**Comment by tylersmith22** [comment]
I think we could revert these settings in settings.py to upstream and put the customizations in our local setting file here (https://github.com/openstack/stx-upstream/blob/master/openstack/python-horizon/centos/files/local_settings.py), like we do with our other changes.  Not sure why we modified this file initially.
Also there's a typo in the comment "user"

**Comment by dsullivanwr** [comment]
That sounds like a much better option, I was wondering why we would do that here. Let me try that fix and I'll update this PR.

**Comment by dsullivanwr** [comment]
It's specific to stx as we aren't using the TOKEN_TIMEOUT_MARGIN parameter (which was introduced in pike).

**Comment by dtroyer** [comment]
LGTM
Thanks David

**Comment by dsullivanwr** [comment]
OK it should be good to go now. I've added another commit to remove the changes from settings.py. Those changes will be made in local_settings.py in stx-upstream. Please squash the commits when you merge the PR.

**Comment by tylersmith22** [comment]
Looks good, thanks for changing

**Pull request merged**
