### PR TITLE
Open vSwitch integration with host and configuration framework

### PR DESCRIPTION
**Pull request by mpeters-wrs**
Integrates the latest Open vSwitch with DPDK into the host management
and configuration framework and configures the default system
vswitch type to be ovs-dpdk.

Story: 2002571

### CODE REVIEW

**Comment by dtroyer** [comment]
I'm not certain we have removed the bits that moved to stx-gui yet.  It looks to me like this needs to go into there instead.

**Comment by mpeters-wrs** [comment]
You are correct.  This same change needs to be propagated to stx-gui.  It was my understanding that stx-horizon is not currently leveraging the extensions from stx-gui, therefore the changes were not pushed to that repo.

**Comment by ediardo** [comment]
Yes, this needs to be to put into the stx-gui. Our internal repository has a branch with all of WRS  customization removed (including the theme). The structure is shaped this way:

- stx-gui-theme: All the branding assets and UI customizations (non-core)
- stx-gui: All of the custom panels, dashboards, etc, JS libraries/scripts
- stx-horizon: current status of this repo - (minus) stx-gui - stx-gui-theme

**Comment by ediardo** [comment]
@dtroyer: stx-gui will still have a strong dependency on stx-horizon until all the core structural changes made to stx-horizon are sorted out.

**Comment by mpeters-wrs** [comment]
What is the recommendation in the short term before the restructure is pushed?  These changes were only testable by making changes to stx-horizon.  Is it testable changes to stx-gui without having the restructured deployment?

**Comment by ediardo** [comment]
Yes @dtroyer. I also agree that this will have to be done at least twice for now. 

@mpeters-wrs: The short-term solution is to merge this patch into this repository. This repo is buildable and tested, the stx-gui plugin is not.

**Comment by dtroyer** [comment]
LGTM

Sounds like you guys have a plan, I added the Story: header to the commit message.

**Comment by ediardo** [comment]
@dtroyer: I'll start building images next week and try my luck with the work done on moving hundreds of files around. Looking forward yo sync up with you and get more understanding of the actual building process.

**Pull request merged**
